# Generated by Django 3.0.5 on 2020-05-16 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=15)),
                ('car_model', models.CharField(max_length=15)),
                ('year_of_issue', models.IntegerField(max_length=4)),
                ('transmition', models.SmallIntegerField()),
                ('color', models.SmallIntegerField()),
            ],
        ),
    ]
